services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_DIR: /data
      BOT_TOKEN: ${BOT_TOKEN:?Set BOT_TOKEN in .env}
#url matching regex is already provided, leave as is
#      REGEX_KEYS: ${REGEX_KEYS:-}
      EXTRA_TRACKING_PARAMS: ${EXTRA_TRACKING_PARAMS:-}
      REPOST_MESSAGE: ${REPOST_MESSAGE:-}
    volumes:
      - bot-data:/data

volumes:
  bot-data: